language: cpp
dist: focal

jobs:
  include:
    - env: CONF=""
      os: osx
      osx_image: xcode12.2
      compiler: clang

    - env: CONF=""
      os: linux
      arch: amd64
      compiler: gcc
      addons: &linuxaddons
        apt:
          packages: &packages
            - libzmq3-dev
            - libzmq5
            - libfdk-aac-dev
            - automake
            - libtool
            - g++-10

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install automake || true
    brew install zeromq || true
    brew install fdk-aac || true
    fi

script:
  - |
    ./bootstrap
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
    export CC=gcc-10
    export CXX=g++-10
    fi
    ./configure $CONF
    make


