language: c++

matrix:
  include:
    - env: CONF=""
      os: osx
      osx_image: xcode11
      compiler: clang

    - env: CONF=""
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: &linuxaddons
        apt:
          sources: &sources
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages: &packages
            - libzmq3-dev
            - libzmq5
            - libfdk-aac-dev
            - automake
            - libtool
            - g++-9

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install automake || true
    brew install zeromq || true
    brew install fdk-aac || true
    fi

script:
  - |
    ./bootstrap
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
    export CC=gcc-9
    export CXX=g++-9
    fi
    ./configure $CONF
    make


